position_control:
  ros__parameters:
    # Position: [ X, Y, Z, Yaw, Duration ]

    sp0: [  0.0,   0.0,   -1.5,  0.0,  10.0 ]
    sp1: [  0.0,   0.0,   -1.5,  0.0,  5.0  ]
    sp2: [  0.0,   0.5,   -1.5,  0.0,  5.0  ]
    sp3: [  0.5,   0.5,   -1.5,  0.0,  5.0  ]
    sp4: [  0.5,   0.0,   -1.5,  0.0,  5.0  ]
    sp4: [  0.0,   0.0,   -1.5,  0.0,  5.0  ]
    sp4: [  0.0,   0.0,    0.0,  0.0,  5.0  ]
